// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

= Timestamp Demo Application

== Timestamp Demo Application Description
Precision Time Protocol (PTP), as defined in IEEE 1588, is utilized to synchronize clocks within a network. 
Accurate timestamps are essential for achieving this synchronization across the network.

Timestamp(TS) Demo Application is used to configure the TS Block of PHYs.

== Directory
* `./mepa_demo/mepa_apps/phy_ts_demo.h` - Header File for TS Demo Application
* `./mepa_demo/mepa_apps/phy_ts_demo.c` - Source File for TS Demo Application


== Procedure to Start/Exit TS Demo Application

To Run TS Demo Application the 'mepa-demo' application needs to be running.
Reffer Section link:#mepa_demo/docs/getting-started[Getting-Started] to know about the procedure 
to run 'mepa-demo' Application.

Once 'mepa-demo' application is started the TS Demo Application can be started with the command
'mepa-cmd ts'.

----
#mepa-cmd ts 
----

The above is used to start the TS Demo Application once it is started it will list the available commands in 
TS Demo Application.

----
#mepa-cmd exit_ts
----

The above command 'exit_ts' is used to Exit the TS Demo Application.

== TS Demo Application Commands

=== Commands Available in TS Demo Application
To List the all available Commands in the TS Demo Application run the below mentioned command.
----
#mepa-cmd ?
----
----
#mepa-cmd ?
 Commands           Arguments                                                                        Description
==================================================================================================================================
exit_ts             |                                                                                 | Exit from Time Stamping Application
 ts_init_conf        |  <port_list> clk_src <clk_src> tx_fifo <tx_fifo> tc_op <tc_op>                  | Initialize TS Block
                     |  dly_10b <dly_10b> tx_af <tx_af> mch <mch>                                      |
 tx_class_conf       |  <port_list> flow_idx <flow_idx> entype <entype>                                | Configures Egress Port Classifier
 tx_clock_conf       |  <port_list> clk_id <clk_id> clk_mode <clk_mode> dly_type <dly_type>            | Configures Egress Port Clock
 rx_class_conf       |  <port_list> flow_idx <flow_idx> entype <entype>                                | Configures Ingress Port Classifier
 rx_clock_conf       |  <port_list> clk_id <clk_id> clk_mode <clk_mode> dly_type <dly_type>            | Configures Ingress Port Clock
 ts_enable           |  <port_list>                                                                    | Enables TS Block
 ts_disable          |  <port_list>                                                                    | Disables TS Block
 ts_ltc_get          |  <port_no>                                                                      | Get Local Time Counter
 ts_ltc_set          |  <port_no> time <sh:sl:ns:ps>                                                   | Set Local Time Counter
 ts_pps_incfg        |  <port_no> clk_sel <clk_sel> pin_sel <pin_sel>                                  | Configure LSC pin for LS controller Input
                     |  pol <pol> sync_mode <sync_mode> ls_ctrl_sel <ls_ctrl_sel>                      |
 ts_pps_outcfg       |  <port_no> clk_sel <clk_sel> pin_sel <pin_sel>                                  | Configure LSC pin for LS controller Output
                     |  pol <pol> sync_mode <sync_mode> ns_en <ns_en> pps_wid <pps_wid> pps_in <pps_in>|
 ts_sertod_incfg     |  <port_no> pin_sel <pin_sel> pol <pol>                                          | Configure Serial ToD Input
                     |  sync_mode <sync_mode> ls_ctrl_sel <ls_ctrl_sel> [load|save]                    |
 ts_sertod_outcfg    |  <port_no> pin_sel <pin_sel> pol <pol>                                          | Configure Serial ToD Output
                     |  sync_mode <sync_mode> wfh <wfh> wfl <wfl>                                      |
 ts_delta_adj        |  <port_no> adj <ns:sns> ls_ctrl_sel <ls_ctrl_sel>                               | Configure delta
 ts_ltc_ls           |  <port_no> pin_action <pin_action> ls_ctrl_sel <ls_ctrl_sel>                    | Local Time Counter
 ts_fifo_get         |  <port_no> sig_mask <sig_mask>                                                  | Get FIFO TS Entry
 ts_delay_set        |  <port_no> timing_mode <timing_mode> delay <delay>                              | Set Time Interval/latency in ns
 ts_delay_get        |  <port_no> timing_mode <timing_mode>                                            | Get Time Interval/latency in ns
 ts_port_state       |                                                                                 | Provides TS State of all Ports
 ts_conf_get         |  <port_no> conf_sel <conf_sel>                                                  | Get TS Configurations
 ts_port_stati       |  <port_no>                                                                      | Get TS Port Statistics
 ts_reset            |  <port_no>                                                                      | Perform TS Block Hard Reset
----

=== TS Block Initialization
Before accessing the TS block, it is mandatory to initialize the TS. This can be done using the following command.
----
#mepa-cmd ts_init_conf <port_list> clk_src <clk_src> tx_fifo <tx_fifo> tc_op <tc_op> dly_10b <dly_10b> tx_af <tx_af> mch <mch>
----

* clk_src <clk_src> - Clock source
    - 0 - Internal, 1 - Rx Port 0, 2 - Rx Port 1, 3 - Rx Port 2, 4 - Rx Port 3, 5 - External


* tx_fifo <tx_fifo> - Tx TS FIFO access clk_mode
    - 0 - Timestamp can be read from normal CPU interface 
    - 1 - Timestamps are pushed out on the SPI interface

* tc_op <tc_op> - TC operating mode
    - 0 - Mode A 
    - 1 - Mode B - Sub local time at ingress and add at egress from CF
    - 2 - Mode C - Sub local time at ingress and add at egress from CF and use 48 bits in CF

* dly_10b <dly_10b> - Delay req/response
    - 0 - Disable
    - 1 - Store 10-byte ingress timestamp for delay request message. Used for auto delay req/response

* mch <mch> 
    - 0 - Disable, 1 - Enable

----
# mepa-cmd ts_init_conf 2 clk_src 0 tx_fifo 0 tc_op 0 dly_10b 0 tx_af 0 mch 0

 ...... TS Block Configured on Port : 1......
----

=== TS Block Egress Port Configuration
The command below are used to configure Egress port Classifier.
----
#mepa-cmd tx_class_conf <port_list> flow_idx <flow_idx> entype <entype>
----

* flow_idx <flow_idx> - Flow index
* entype <entype> - Encapsulation type
    - 0 - None, 1 - Eth PTP, 2 - Eth IP PTP, 3 - Eth IP IP PTP, 4 - Eth Eth PTP, 5 - Eth Eth IP PTP,
    - 6 - Eth MPLS IP PTP, 7 - Eth MPLS Eth PTP, 8 - Eth MPLS Eth IP PTP

Based on Encapsulation type selected, Ethernet/IP Header classification parameters will be fetched from 
User

----
#mepa-cmd tx_class_conf 2 flow_idx 0 entype 3

 ------------------------------------------

 First Layer Ethernet Header Configuration

 ------------------------------------------

 Match PTP Packet MAC types [0 : Any, 1 : 48 Bit, 2: Any Unicast, 3: Any Multicast]: 2

 Enter MAC address (Format- xx:xx:xx:xx:xx:xx): 0:0:0:0:0:1

 VLAN Check [0 : parse VLAN tag if any, 1: verify configured VLAN tag configuration]: 0

 IP Version [0 : ip4v, 1: ip6v]: 1

 Enter First Layer IPv6 address (format - x:x:x:x:x:x:x:x): 2000:0:0:0:0:0:0:2

 Enter Second Layer IPv6 address (format - x:x:x:x:x:x:x:x): 2000:0:0:0:0:0:0:3

 ...... TS Tx classifier Configuration on Port : 1......
----

The command below are used to configure Egress port Clock.

----
 #mepa-cmd tx_clock_conf <port_list> clk_id <clk_id> clk_mode <clk_mode> dly_type <dly_type>
----

* clk_id <clk_id> - Clock ID
* clk_mode <clk_mode> - PTP Clock Operational Mode
    - 0 - None, 1 - BC1STEP, 2 - BC2STEP, 3 - TC1STEP, 4 - TC2STEP
* dly <dly_type> - PTP delay measurement method
    - 0 - Peer-to-Peer delay measurement method 
    - 1 - End-to-End delay measurement method

----
 # mepa-cmd tx_clock_conf 2 clk_id 0 clk_mode 1 dly_type 1
 ...... TS Tx Clock Configuration on Port : 1.....
----

=== TS Block Ingress Port Configuration
The command below are used to configure Ingress port Classifier.
----
#mepa-cmd rx_class_conf <port_list> flow_idx <flow_idx> entype <entype>
----

* flow_idx <flow_idx> - Flow index
* entype <entype> - Encapsulation type
    - 0 - None, 1 - Eth PTP, 2 - Eth IP PTP, 3 - Eth IP IP PTP, 4 - Eth Eth PTP, 5 - Eth Eth IP PTP,
    - 6 - Eth MPLS IP PTP, 7 - Eth MPLS Eth PTP, 8 - Eth MPLS Eth IP PTP

Based on Encapsulation type selected, Ethernet/IP Header classification parameters will be fetched from 
User

----
 #mepa-cmd rx_class_conf 2 flow_idx 0 entype 3

 ------------------------------------------

 First Layer Ethernet Header Configuration

 ------------------------------------------

 Match PTP Packet MAC types [0 : Any, 1 : 48 Bit, 2: Any Unicast, 3: Any Multicast]: 2

 Enter MAC address (Format- xx:xx:xx:xx:xx:xx): 0:0:0:0:0:1

 VLAN Check [0 : parse VLAN tag if any, 1: verify configured VLAN tag configuration]: 0

 IP Version [0 : ip4v, 1: ip6v]: 1

 Enter First Layer IPv6 address (format - x:x:x:x:x:x:x:x): 2000:0:0:0:0:0:0:2

 Enter Second Layer IPv6 address (format - x:x:x:x:x:x:x:x): 2000:0:0:0:0:0:0:3

 ...... TS Rx classifier Configuration on Port : 1......
----

The command below are used to configure Ingress port Clock.

----
 #mepa-cmd rx_clock_conf <port_list> clk_id <clk_id> clk_mode <clk_mode> dly_type <dly_type>
----

* clk_id <clk_id> - Clock ID
* clk_mode <clk_mode> - PTP Clock Operational Mode
    - 0 - None, 1 - BC1STEP, 2 - BC2STEP, 3 - TC1STEP, 4 - TC2STEP
* dly <dly_type> - PTP delay measurement method
    - 0 - Peer-to-Peer delay measurement method 
    - 1 - End-to-End delay measurement method

----
 # mepa-cmd rx_clock_conf 1 clk_id 0 clk_mode 1 dly_type 1
 ...... TS Rx Clock Configuration on Port : 0.....
----

=== TS Block Enable/Disable
Following command is used to Enable/Disable TS block.

    * mepa-cmd ts_enable <port_list>
    * mepa-cmd ts_disable <port_list>

----
# mepa-cmd ts_enable 1,2

 ...... TS Block Enabled on Port : 0......

 ...... TS Block Enabled on Port : 1......
----

=== TS Block Local Time Counter
The local time counter keeps the local time for the device and the time is monitored and synchronized to
an external reference by the CPU. 

==== PPS 
PPS(Pulse Per Second) is used to provide a precise timing reference by generating pulse at the start of 
each second, which can be used to align clocks in different systems. 

The command below is used to configure LSC pin as Input.

----
 #mepa-cmd ts_pps_incfg <port_no> clk_sel <clk_sel> pin_sel <pin_sel> pol <pol> sync_mode <sync_mode> ls_ctrl_sel <ls_ctrl_sel>
----

* clk_sel <clk_sel> - Selects which PTP1588_LSC pin to use for synchronization
0-3: PTP1588_LSC_PIN[x]
4: No clock is used in operation
5: L/S reference clock
6: L/S reference clock div2
7: L/S reference clock div4
8: L/R reference clock div5
9: L/R reference clock div8
* pin_sel <pin_sel> - Selects which PTP1588_LSC pin to use as input pps
    0: PTP1588_LSC[0]
    1: PTP1588_LSC[1]
    2: PTP1588_LSC[2]
    3: PTP1588_LSC_3_P/N
* pol <pol> - Polarity of the PTP pins.
    0: Active high
    1: Active low
* sync_mode <sync_mode> - Sync Mode
    0 - Immediate, 1 - One Shot, 2 - Continuous
* ls_ctrl_sel <ls_ctrl_sel>
    0 - LS0, 1 - LS1, 2 - LS2, 3 - LS3
----
 # mepa-cmd ts_pps_incfg 2 clk_sel 4 pin_sel 0 pol 0 sync_mode 0 ls_ctrl_sel 0

 ...... TS PPS Input Configured for Port : 1......
----

The command below is used to configure LSC pin as Output.
----
 #mepa-cmd ts_pps_outcfg <port_no> clk_sel <clk_sel> pin_sel <pin_sel> pol <pol> sync_mode <sync_mode> ns_en <ns_en> pps_wid <pps_wid> pps_in <pps_in>
----
* clk_sel <clk_sel> - Selects which PTP1588_LSC pin to use for synchronization
0-3: PTP1588_LSC_PIN[x]
4: No clock is used in operation
5: L/S reference clock
6: L/S reference clock div2
7: L/S reference clock div4
8: L/R reference clock div5
9: L/R reference clock div8
* pin_sel <pin_sel> - Selects which PTP1588_LSC pin to use as input pps
    0: PTP1588_LSC[0]
    1: PTP1588_LSC[1]
    2: PTP1588_LSC[2]
    3: PTP1588_LSC_3_P/N
* pol <pol> - Polarity of the PTP pins.
    0: Active high
    1: Active low
* sync_mode <sync_mode> - Sync Mode
    0 - Immediate, 1 - One Shot, 2 - Continuous
* ns_en <ns_en> - Nanoseconds bitenble
* pps_wid <pps_wid> - PPS Pulse Width
* pps_in <pps_in> - PPS Pulse Interval

----
 # mepa-cmd ts_pps_outcfg 2 clk_sel 4 pin_sel 1 pol 1 sync_mode 1 ns_en 1 pps_wid
 2 pps_in 1

 ...... TS PPS Output Configured for Port : 1......
----

==== Serial ToD
Serial ToD refers to the transmission of Time of Day (ToD) information over a serial interface.

The command below is used to configure Serial ToD as Input.
----
 #mepa-cmd ts_sertod_incfg <port_no> pin_sel <pin_sel> pol <pol> sync_mode <sync_mode> ls_ctrl_sel <ls_ctrl_sel> [load|save]
----
* pin_sel <pin_sel> - Selects which PTP1588_LSC pin to use as input pps
    0: PTP1588_LSC[0]
    1: PTP1588_LSC[1]
    2: PTP1588_LSC[2]
    3: PTP1588_LSC_3_P/N
* pol <pol> - Polarity of the PTP pins.
    0: Active high
    1: Active low
* sync_mode <sync_mode> - Sync Mode
    0 - Immediate, 1 - One Shot, 2 - Continuous
* ls_ctrl_sel <ls_ctrl_sel>
    0 - LS0, 1 - LS1, 2 - LS2, 3 - LS3
* [load|save] - Load Enable or Save Enable
----
 #mepa-cmd ts_sertod_incfg 2 pin_sel 2 pol 0 sync_mode 0 ls_ctrl_sel 1 load

 ...... TS Serial ToD Input Configured for Port : 1......
----
The command below is used to configure Serial ToD as Output.
----
 #mepa-cmd ts_sertod_outcfg <port_no> pin_sel <pin_sel> pol <pol> sync_mode <sync_mode> wfh <wfh> wfl <wfl>
----
* pin_sel <pin_sel> - Selects which PTP1588_LSC pin to use as input pps
    0: PTP1588_LSC[0]
    1: PTP1588_LSC[1]
    2: PTP1588_LSC[2]
    3: PTP1588_LSC_3_P/N
* pol <pol> - Polarity of the PTP pins.
    0: Active high
    1: Active low
* sync_mode <sync_mode> - Sync Mode
    0 - Immediate, 1 - One Shot, 2 - Continuous
* wfh <wfh> - Waveform High Period
* wfl <wfl> - Waveform Low Period
----
 #mepa-cmd ts_sertod_outcfg 2 pin_sel 2 pol 0 sync_mode 0 wfh 2 wfl 1

 ...... TS Serial ToD Output Configured for Port : 1......
----
==== Delta Adjustment
Delta is used to fine-tune the ToD to ensure that the time information is as accurate as possible and
this adjustment can be done using following command

----
 #mepa-cmd ts_delta_adj <port_no> adj <ns:sns> ls_ctrl_sel <ls_ctrl_sel>
----
* adj <ns:sns> - Time adjustment in nanoseconds and subnanoseconds
* ls_ctrl_sel <ls_ctrl_sel>
    0 - LS0, 1 - LS1, 2 - LS2, 3 - LS3

----
 #mepa-cmd ts_delta_adj 2 adj 2:5 ls_ctrl_sel 1

 ...... TS LTC Delta Adjust Configured for Port : 1......
----
==== PTP Action 
The command "ts_ltc_ls" will trigger the start of selected operation. All other setups have to be 
completed before executing this command.
----
#mepa-cmd ts_ltc_ls <port_no> pin_action <pin_action> ls_ctrl_sel <ls_ctrl_sel>
----
* pin_action <pin_action> 
    0 - Load, 1 - Save, 2 - Clear, 3 - Delta, 4 - Waveform, 5 - Time of Day
* ls_ctrl_sel <ls_ctrl_sel>
    0 - LS0, 1 - LS1, 2 - LS2, 3 - LS3
----
 #mepa-cmd ts_ltc_ls 2 pin_action 0 ls_ctrl_sel 0

 ...... TS LTC Action Load performed on Port : 1......
----
==== LTC Value
The following command is used to get LTC value.

    * mepa-cmd ts_ltc_get <port_no>

----
    # mepa-cmd ts_ltc_get 2

    ...... TS Local Time Clock on Port : 1......
    seconds.high: 0
    seconds.low: 65
    nanoseconds: 656032937
    picoseconds: 76
----

The following command is used to get LTC value.

    * mepa-cmd ts_ltc_set <port_no> time <sh:sl:ns:ps>

----
    # mepa-cmd ts_ltc_set 2 time 0:1:337078563:169

    ...... TS LTC Set on Port : 1......
----

=== TS Time Interval/latency
The following command is used to set Time Interval/latency.
----
# mepa-cmd ts_delay_set <port_no> timing_mode <timing_mode> delay <delay>
----
* timing_mode <timing_mode>
    0 - Delay Asymmetry, 1 - Path Delay, 2 - Egress Latency, 3 - Ingress Latency
* delay <delay> 
    Time Interval in ns
----
# mepa-cmd ts_delay_set 2 timing_mode 1 delay 2.5

...... TS Set Path Delay on Port : 1 ......
----
The following command is used to get Time Interval/latency.
----
# mepa-cmd ts_delay_get <port_no> timing_mode <timing_mode>
----
* timing_mode <timing_mode>
    0 - Delay Asymmetry, 1 - Path Delay, 2 - Egress Latency, 3 - Ingress Latency

----
# mepa-cmd ts_delay_get 2 timing_mode 1

 ...... TS Path Delay on Port : 1......

 Delay: 2.500000 ns (Equivalent hex value is 0x280)
----

=== TS FIFO
To get Timestamp entries for modes like BC2STEP Egress the command 'ts_fifo_get' is used.
----
 #mepa-cmd ts_fifo_get <port_no> sig_mask <sig_mask>
----
    * sig_mask <sig_mask> - Frame signature Mask
    - 0x01 - Source IP
    - 0x02 - Destination IP
    - 0x04 - Message IP
    - 0x08 - Domain Number
    - 0x10 - Source Port Identity
    - 0x20 - PTP frame Sequence ID
    - 0x40 - Destination MAC address

----
#mepa-cmd ts_fifo_get 2 sig_mask 0x7C
Number of entries: 4
Entry 0:
  Signal:
    Message Type: 0
    Domain Number: 0
    Source Port Identity: 00:00:00:00:00:00:00:00:00:00
    Sequence ID: 0
    CRC Source Port: 0
    Has CRC Source: False
  Timestamp:
    Seconds: 092
    Nanoseconds: 660411039
    Picoseconds: 0
Entry 1:
  Signal:
    Message Type: 0
    Domain Number: 0
    Source Port Identity: 00:00:00:00:00:00:00:00:00:00
    Sequence ID: 0
    CRC Source Port: 0
    Has CRC Source: False
  Timestamp:
    Seconds: 092
    Nanoseconds: 661391456
    Picoseconds: 0
Entry 2:
  Signal:
    Message Type: 0
    Domain Number: 0
    Source Port Identity: 00:00:00:00:00:00:00:00:00:00
    Sequence ID: 0
    CRC Source Port: 0
    Has CRC Source: False
  Timestamp:
    Seconds: 092
    Nanoseconds: 662371875
    Picoseconds: 36
Entry 3:
  Signal:
    Message Type: 0
    Domain Number: 0
    Source Port Identity: 00:00:00:00:00:00:00:00:00:00
    Sequence ID: 0
    CRC Source Port: 0
    Has CRC Source: False
  Timestamp:
    Seconds: 092
    Nanoseconds: 663352262
    Picoseconds: 0

 ...... TS FIFO Get on Port : 1......
----


=== TS Block Status
To Check whether the TS is enabled or disabled on the Port the command 'ts_port_state' is used.

    * mepa-cmd ts_port_state
----
 # mepa-cmd ts_port_state
 Port    Status
 ----------------------
 1       Disabled
 2       Enabled
 3       Disabled
 4       Disabled
 5         --
 6         --
 7         --
 8         --
 9         --
 10        --
 11        --
 12        --
 13        --
 14        --
 15        --
 16        --
 17        --
 18        --
 19        --
 20        --
----

=== TS Block Configuration
To Check TS block configurations 'ts_conf_get' is used.
----
 #mepa-cmd ts_conf_get <port_no> conf_sel <conf_sel>
----
    * conf_sel <conf_sel> 
    - 0 - TS Block Init Configuration
    - 1 - TS Tx Classifier Configuration
    - 2 - TS Tx Clock Configuration
    - 3 - TS Rx Classifier Configuration
    - 4 - TS Rx Clock Configuration
----
# mepa-cmd ts_conf_get 2 conf_sel 0

---------------TS Init Configuration: Port 1-------------------------
 clk_freq: MEPA_TS_CLOCK_FREQ_15625M

 clk_src: MEPA_TS_CLOCK_SRC_FROM_RX_PORT1

 rx_ts_pos: MEPA_TS_RX_TIMESTAMP_POS_IN_PTP

 rx_ts_len: MEPA_TS_RX_TIMESTAMP_LEN_30BIT

 tx_fifo_mode: MEPA_TS_FIFO_MODE_NORMAL

 tx_ts_len: MEPA_TS_FIFO_TIMESTAMP_LEN_4BYTE

 tx_fifo_spi_conf: 0

 auto_clear_ls: 0

 tc_op_mode: MEPA_TS_TC_OP_MODE_A

 dly_req_recv_10byte_ts: 0

 tx_auto_followup_ts: 187

 mch_pch_conf: { pch_en: 127, save_ts_with_crc_err: 0, mch_en: 0, ts_len_ing: MEPA_MCH_TS_32NS_
ONS, ts_len_egr: MEPA_MCH_TS_32NS_ONS }
----
=== TS Statistics
The following command is used get TS Statistics for selected port.

    * mepa-cmd ts_port_stati <port_no>

----
# mepa-cmd ts_port_stati 2
 Timestamp Port Statistics
 ============================
 Ingress Preamble Shrink Errors: 0
 Egress Preamble Shrink Errors: 0
 Ingress FCS Errors: 0
 Egress FCS Errors: 0
 Ingress Frame Modification Count: 0
 Egress Frame Modification Count: 0
 Timestamp FIFO Transmit Count: 0
 Timestamp FIFO Drop Count: 0
----

=== TS Reset
The following command is used to hard reset TSU for selected port.

    * mepa-cmd ts_reset <port_no>

----
# mepa-cmd ts_reset 2

 ...... TS Reset on Port : 1......
----

